config/routes.rb
Rails.application.routes.draw do
  root 'tasks#index'
  resources :tasks do
    resources :child_tasks, only: [:create, :destroy, :edit]
    put :sort
  end

  post 'tasks/:task_id/child_tasks/:id/toggle' => 'child_tasks#toggle'

  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users

  # get 'effects#index'
  # get 'article'=> 'effects#article'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/child_task.rb
class ChildTask < ApplicationRecord
  belongs_to :task
end

app/models/task.rb
class Task < ApplicationRecord
  # ActiveRecordがtypeというカラム名を使用するため、typeカラムは使用できない。以下はtypeカラムを使用するための措置。
  self.inheritance_column = :_type_disabled
  has_many :child_tasks, dependent: :destroy

  # D&Dによるタスク移動のための記述
  include RankedModel
  ranks :row_order
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  # 正規表現による有効なメールアドレスを定義し、バリデーションに利用。
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
             format: { with: VALID_EMAIL_REGEX },
            # 大文字小文字を無視した一意性のバリデーション
             uniqueness: { case_sensitive: true }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # ↓ SessionsHelperを全コントローラから使えるようにする
  include SessionsHelper
  before_action :logged_in_user

  def logged_in_user
    unless logged_in?
      redirect_to login_url
    end
  end
end

app/controllers/child_tasks_controller.rb
class ChildTasksController < ApplicationController

  def create
    @task = Task.find(params[:task_id])
    @child_task = @task.child_tasks.create(child_task_params)
  #   respond_to do |format|
  #     if @child_task.save
  #       format.html {render root_path}
  #       format.js
  #     else
    redirect_to root_path
  #   end
  # end
end

  def edit
  end

  def destroy
    @child_task = ChildTask.find(params[:id])
    @child_task.destroy
    redirect_to root_path
  end

  def toggle
    # ↓redirect_to root_pathと同義
    render nothing: true
    @child_task = ChildTask.find(params[:id])
    # ↓child_taskのdoneの値をひっくり返す
    @child_task.done = !@child_task.done
    @child_task.save
  end

  private

    def child_task_params
      params.require(:child_task).permit(:title)
    end
end

app/controllers/effects_controller.rb
class EffectsController < ApplicationController

  def index
  end

  def article
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :logged_in_user

  def new
  end

  def create
    # userをDBから引っ張ってくる。
    user = User.find_by(email: params[:session][:email].downcase)
    # userがDBにいる かつ　認証が成功した場合
    if user && user.authenticate(params[:session][:password])
      # SessionsHelperに定義したlog_inメソッドを呼び出し。
      log_in user
      redirect_to root_url
    else
    flash.now[:danger] = 'Invalid email/password combination'
    render 'new'
    end
  end

  def destroy
    log_out
    redirect_to login_url
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @task = Task.new
    @tasks = Task.rank(:row_order)
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      respond_to do |format|
        format.html {redirect_to root_path}
        format.json
      end
    else
      redirect_to root
    end
  end

  def edit
  end

  def update
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to root_path
  end

  def sort
    task = Task.find(params[:task_id])
    task.update(task_row_params)
    render nothing: true
  end

  private
  def task_params
    params.require(:task).permit(:task, :type)
  end

  def task_row_params
    params.require(:task).permit(:task, :row_order_position)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :logged_in_user

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      # signupと同時にlogin
      log_in @user
      flash[:success] = "Welcome to the Mienya!"
      # ↓ redirect_to user_url(@user)
      redirect_to root_url
    else
      render 'new'
    end
  end


  def show
    @user = User.find(params[:id])
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/child_tasks_helper.rb
module ChildTasksHelper
end

app/helpers/effects_helper.rb
module EffectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # 渡されたユーザーでログインする
  def log_in(user)
    session[:user_id] = user.id
  end

  # 現在ログイン中のユーザーを返す (いる場合)
  def current_user
    # 左辺がnilなら右辺を代入する。
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # ユーザーがログインしていればtrue、その他ならfalseを返す
  def logged_in?
    !current_user.nil?
  end

  # 現在のユーザーをログアウトする
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/child_tasks/create.js.erb
$('#ajax-childtask-create').html("<%= j(render child_task: child_task,task: task)=%>")

app/views/layouts/_footer.html.haml
.index-footer-fixed
  .copyright-section
    %p © Copyright 2017 Mienya All rights reserved.

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title InterestingEffect
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = favicon_link_tag
  %body
    -flash.each do |message_type, message|
      = content_tag(:div, message, class: "alert alert-#{message_type}")
    = yield
    = render 'layouts/footer.html.haml'

app/views/shared/_error_messages.html.haml
- if @user.errors.any?
  #error_explanation
    .alert "The form contains #{pluralize(@user.errors.count, "error")}"

    %ul
      - @user.errors.full_messages.each do |msg|
        %li
          = msg

app/views/tasks/_child_task.html.haml
.task-box__second
  .task-box__second__status
    = check_box_tag '', '', child_task.done, 'data-id': child_task.id, 'data-task_id': child_task.task_id, id: "checkbox#{child_task.id}"
    = label_tag "checkbox#{child_task.id}", "", class: "check_css"
  .task-box__second__name
    %p
      = child_task.title
  .task-box__second__deadline
  .task-box__second__func
    .task-box__second__func__icon
      %i.fa.fa-plus-square.fa-fw
    .task-box__second__func__icon
      %i.fa.fa-edit.fa-fw
    .task-box__second__func__icon
      = link_to "/tasks/#{task.id}/child_tasks/#{child_task.id}", method: :delete, data: {confirm: "are you sure?"} do
        %i.fa.fa-trash.fa-fw

app/views/tasks/_task.html.haml
.task-box-wrapper.item{data: { model_name: task.class.name.underscore, update_url: task_sort_path(task) }}
  .task-box
    .task-box__status
    .task-box__name
      %p
        = task.task
    .task-box__deadline
    .task-box__func
      .task-box__func__icon
        %i.fa.fa-plus-square.fa-fw
      .task-box__func__icon
        %i.fa.fa-edit.fa-fw
      .task-box__func__icon
        = link_to task_path(task), method: :delete, data: {confirm: "are you sure?"} do
          %i.fa.fa-trash.fa-fw
  .task-registration-field.form-controll
    = form_for [task, task.child_tasks.build], html: {class: 'child_task-form'} do |c|
      .task-registration-box
        %span
          =c.text_field :title, placeholder: "what is your task?", class: "form-box"
          =c.label :title, class: "form-name"
          =c.hidden_field :type, value: "0"
          =c.submit "Create!", class: "form-button"
  .child_task-field#ajax-childtask-create
    -# 子タスクを表示。_child_task.html.hamlをレンダリング。.first(task.child_tasks.length-1)で繰返し回数を制御
    -task.child_tasks.first(task.child_tasks.length-1).each do |child_task|
      = render "child_task", child_task: child_task,task: task

app/views/tasks/create.html.haml
%h1 Tasks#create
%p Find me in app/views/tasks/create.html.erb

app/views/tasks/create.js.erb
$('#ajax-create').html("<%= j(render @tasks) %>")

app/views/tasks/edit.html.haml
%h1 Tasks#edit
%p Find me in app/views/tasks/edit.html.erb

app/views/tasks/index.html.haml
.index-header-fixed
  %h1.title Mienya
  / =image_tag "Mienya-logo.png", class: "title-logo"
  .task-registration-field
    = form_for @task, remote: true do |f|
      .task-registration-box
        %span
          =f.text_field :task, placeholder: "what is your task?", class: "form-box"
          =f.label :task, class: "form-name"
          =f.hidden_field :type, value: "0"
          =f.submit "Create!", class: "form-button"

.task-field
  .task-box-area#ajax-create.table-sortable
    -# _task.html.hamlをレンダリング
    = render @tasks

-# 仮置きでtaskの最下に配置しています。
.logout-button-section
  - if logged_in?
    .user-button
      =link_to "LOGOUT", logout_path, method: :delete
  - else
    .user-button
      =link_to "LOGIN", login_path
    .user-button
      =link_to "SIGNUP", signup_path

app/views/tasks/new.html.haml
%h1 Tasks#new
%p Find me in app/views/tasks/new.html.erb

app/views/tasks/update.html.haml
%h1 Tasks#update
%p Find me in app/views/tasks/update.html.erb

app/views/users/new.html.haml
.signup-wrapper
  .signup-form-section
    .title
      = image_tag "Mienya2-logo.png", class: "title-logo"
      / %h1.title Mienya

    .signup-form
      %h1 Sign up
      .transparent-bothends
      = form_for @user, url: signup_path do |f|
        = render 'shared/error_messages'

        .signup-form__name.form-item
          = f.label :name
          = f.text_field :name, class: 'form-control'

        .signup-form__email.form-item
          = f.label :email
          = f.email_field :email, class: 'form-control'

        .signup-form__password.form-item
          = f.label :password
          = f.password_field :password, class: 'form-control'

        .signup-form__password_confirmation.form-item
          = f.label :password_confirmation, "Confirmation"
          = f.password_field :password_confirmation, class: 'form-control'

          = f.submit "Create my account", class: "signup-button"

app/views/users/show.html.erb
= @user.name, =@user.email

app/views/users/show.html.haml
= @user.name, =@user.email